safe: true
paginate: 5
highlighter: pygments
markdown: kramdown

name: com.tilmonedwards._
description: "Software Developer, Bassist, Pretty Cool Guy."
url: http://tilmonedwards.com
author: Sean Edwards

exclude:
  - dot/*.dot
