safe: true
paginate: 5
highlighter: pygments
markdown: kramdown

name: com.tilmonedwards._
description: "Software Developer, Bassist, Pretty Cool Guy."
url: http://tilmonedwards.com
author: Sean Edwards

exclude:
  - dot/*.dot

defaults:
  - scope:
      path: ""
    values:
      layout: default
      nav: true
      ads: true

  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true

  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      comments: false
      #ads: false
